version: "3"
services:
  node:
    container_name: node
    restart: always
    build: .
    command: "npm run-script watch"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_USER=user
      - MONGODB_PASS=pass
      - SECRET=c8fdcea54d5a
    volumes:
      - .:/home/app
      - /home/app/node_modules

    expose:
      - "3000"
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
